//Components
import Head from "next/head";
import Product from "../components/Product";
//styles
import { Gallery } from "../styles/Gallery";
//graphql
import { useQuery } from "urql";
import { PRODUCT_QUERY } from "../lib/query";

export default function Home() {
  // fetch products from strapi
  const [results] = useQuery({ query: PRODUCT_QUERY });
  const { data, fetching, error } = results;

  //Check fro the data coming in
  if (fetching) return <p>Loading</p>;
  if (error) return <p>{error.message}</p>;
  const products = data.products.data;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <Gallery>
          {products.map((product) => (
            <Product product={product} key={product.attributes.slug} />
          ))}
        </Gallery>
      </main>
    </div>
  );
}
